# このワークフローはGitHubによって認定されていないアクションを使用します。
# それらはサードパーティによって提供され、
# 別個の利用規約、プライバシーポリシー、
# ドキュメントを参照してください。

# GitHub では、コミット SHA にアクションをピン留めすることが推奨されます。
# 新しいバージョンを取得するには、SHA を更新する必要があります。
# タグまたはブランチを参照することもできますが、アクションは警告なしに変更される可能性があります。
permissions:
  contents: read
  packages: write

name: Publish Docker image

on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - series: innovation
            version: 9.3
            extra_tag: Innovation
          - series: lts
            version: 8.4
            extra_tag: LTS
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: snickerjp/docker-mysql-shell
          tags: |
            type=semver,pattern={{version}}
            type=raw,value=${{ matrix.version }}
            type=raw,value=${{ matrix.series }}
            type=raw,value=latest,enable=${{ matrix.series == 'lts' }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./docker/${{ matrix.series }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
