name: Build MySQL Shell Docker Images

permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - main
      - develop
      - feat-*
    paths:
      - docker/**
      - .github/workflows/docker-build.yml
  pull_request:
    branches:
      - main
      - develop
    paths:
      - docker/**
      - .github/workflows/docker-build.yml
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - series: innovation
            version: 9.3
            extra_tag: Innovation
          - series: lts
            version: 8.4
            extra_tag: LTS

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./docker/${{ matrix.series }}
          push: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/main' }}
          tags: |
            snickerjp/docker-mysql-shell:${{ matrix.version }}
            snickerjp/docker-mysql-shell:${{ matrix.extra_tag }}
            ${{ matrix.series == 'lts' && 'snickerjp/docker-mysql-shell:latest' || '' }}

      - name: Update Docker Hub description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: snickerjp/docker-mysql-shell
          readme-filepath: ./README.md
