name: Review Feature Branch

on:
  pull_request:
    branches:
      - develop
    types: [opened, synchronize, reopened]

permissions: read-all

jobs:
  review:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - series: innovation
            version: 9.2
          - series: lts
            version: 8.4

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build test
        uses: docker/build-push-action@v5
        with:
          context: ./docker/${{ matrix.series }}
          push: false
          load: true

      - name: Add PR Review Comment
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.payload.pull_request.number;
            const branchName = context.payload.pull_request.head.ref;
            
            if (!branchName.startsWith('feat-')) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                body: '⚠️ Warning: Branch name should start with `feat-`'
              });
            }